- name: dotfiles
  tags: dotfiles
  block:
    - name: Unstow dotfiles
      shell: stow -D dotfiles

    - name: Uninstall Stow
      community.general.homebrew:
        name: stow
        state: absent
