- name: ssh
  tags: ssh
  block:
    - name: Ensure .ssh directory exists.
      file:
        dest: "{{ ssh_dest_key | dirname }}"
        mode: 0700
        state: directory

    - name: Install ssh key
      copy:
        src: "{{ ssh_source_key }}"
        dest: "{{ ssh_dest_key }}"
        mode: 0600

    - name: Install ssh key public
      copy:
        src: "{{ ssh_source_key }}.pub"
        dest: "{{ ssh_dest_key }}.pub"
        mode: 0644

    - name: Set authorized key took from file
      authorized_key:
        user: "{{ lookup('env', 'USER') }}"
        state: present
        key: "{{ lookup('file', lookup('env','HOME') + '/.ssh/id_ed25519.pub') }}"
