- name: terminal
  tags: terminal
  block:
    - name: Install tldr npm package
      shell: npm i -g tldr && tldr curl

    - name: Install commitizen npm package
      shell: npm i -g commitizen

    - name: Install tree
      community.general.homebrew:
        name: tree

    - name: Install bat
      community.general.homebrew:
        name: bat

    - name: Install iTerm2
      community.general.homebrew_cask:
        name: iterm2

    - name: Clone dracula theme
      ansible.builtin.git:
        repo: "https://github.com/dracula/iterm.git"
        dest: "{{ lookup('env', 'HOME') }}/.dracula-iterm2"
        update: yes

    - name: Install awscli package
      pip:
        name: awscli
