- name: zsh
  tags: zsh
  block:
    - name: Check that the oh-my-zsh exists
      stat:
        path: $HOME/.oh-my-zsh
      register: oh_my_stat

    - name: Uninstall Oh-My-Zsh
      shell: sh ~/.oh-my-zsh/tools/uninstall.sh
      become_user: "{{ lookup('env', 'USER') }}"
      when: oh_my_stat.stat.exists == True

    - name: Change shell to bash
      shell: chsh -s $(which bash)
